# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - workspace_publish

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Workspace Arm Templates'
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/WorkspaceArmTemplates'
    artifact: 'WorkspaceArmTemplates'
    publishLocation: 'pipeline'
