# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - workspace_publish

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: CmdLine@2
  inputs:
    script: |
      echo "Structure of work folder of this pipeline:"
      tree $(Agent.WorkFolder)\1 /f
      
      echo "Build.ArtifactStagingDirectory:" 
      
      echo "$(Build.ArtifactStagingDirectory)"
      
      echo "Build.BinariesDirectory:" 
      
      echo "$(Build.BinariesDirectory)"
      
      echo "Build.SourcesDirectory:"
      
      echo "$(Build.SourcesDirectory)"
- task: PublishPipelineArtifact@1
  displayName: 'Publish Workspace Arm Templates'
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/.git/origin/workspace_publish'
    artifact: 'workspace_arm_templates'
    publishLocation: 'pipeline'
