# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/Planning-Inspectorate/data-model/main/schemas/employee.schema.json
#   timestamp: 2024-01-04T16:34:30+00:00

from __future__ import annotations

from pydantic import BaseModel


class Employee(BaseModel):
    id: str
    firstName: str
    lastName: str
