# generated by datamodel-codegen:
#   filename:  nsip-exam-timetable-submission.schema.json
#   timestamp: 2023-12-14T15:05:02+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Status(Enum):
    SUCCESS = 'SUCCESS'
    VIRUS_DETECTED = 'VIRUS_DETECTED'
    FAILURE = 'FAILURE'


class NsipExamTimetableSubmission(BaseModel):
    """
    Result of processing a new exam timetable submission
    """

    status: Status
    deadline: str
    submissionType: str
    blobGuid: str
    documentName: str
