# generated by datamodel-codegen:
#   filename:  employee.schema.json
#   timestamp: 2023-12-14T15:02:13+00:00

from __future__ import annotations

from pydantic import BaseModel


class Employee(BaseModel):
    id: str
    firstName: str
    lastName: str
