# generated by datamodel-codegen:
#   filename:  interested-party.schema.json
#   timestamp: 2023-12-14T15:02:50+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, constr


class ContactMethod(Enum):
    email = "email"
    post = "post"


class Address(BaseModel):
    addressLine1: str = Field(..., examples=["National Traffic Operations Centre"])
    addressLine2: str | None = Field(
        None, examples=["3 Ridgeway, Quinton Business Park"]
    )
    town: str = Field(..., examples=["Birmingham"])
    postcode: str = Field(..., examples=["B32 1AF"])
    country: str | None = Field(None, examples=["England"])


class InterestedParty(BaseModel):
    """
    Subset of Pins Data Model [Service User]
    """

    id: float | None = Field(None, examples=[18])
    interestedPartyNumber: str | None = Field(None, examples=["IP1234"])
    firstName: str | None = Field(None, examples=["Alan"])
    lastName: str | None = Field(None, examples=["Turing"])
    under18: bool | None = None
    organisationName: constr(pattern=r"^.*$") | None = Field(
        "", examples=["National Highways"], title="Name"
    )
    jobTitle: str | None = Field(None, examples=["Communications Manager"])
    contactMethod: ContactMethod | None = None
    email: str | None = Field(
        None, examples=["alan.turing@planninginspectorate.gov.uk"]
    )
    phoneNumber: str | None = Field(None, examples=["0137732432"])
    address: Address | None = Field(None, title="Address")
