# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/Planning-Inspectorate/data-model/main/schemas/case-schedule.schema.json
#   timestamp: 2024-01-04T16:34:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class CaseSchedule(BaseModel):
    pass
