# generated by datamodel-codegen:
#   filename:  service-user.schema.json
#   timestamp: 2023-12-14T15:08:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class ServiceUserType(Enum):
    """
    Type or category of the service user.
    """

    Applicant = "Applicant"
    Appellant = "Appellant"
    Agent = "Agent"
    RepresentationContact = "RepresentationContact"
    Subscriber = "Subscriber"


class ServiceUser(BaseModel):
    """
    Service User of the planning inspectorate. Also contains role information by combining serviceUserType and caseReference.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., examples=["12345"])
    """
    A unique identifier for the entity.
    """
    salutation: str | None = Field(None, examples=["Mr"])
    """
    A formal greeting, e.g., Mr, Mrs, Ms.
    """
    firstName: str | None = Field(None, examples=["John"])
    """
    The first name of the individual.
    """
    lastName: str | None = Field(None, examples=["Doe"])
    """
    The last name of the individual.
    """
    addressLine1: str | None = Field(None, examples=["123 Elm Street"])
    """
    The first line of the address.
    """
    addressLine2: str | None = Field(None, examples=["Apt 4B"])
    """
    The second line of the address, usually includes suite or apartment number.
    """
    addressTown: str | None = Field(None, examples=["Springfield"])
    """
    The town or city of the address.
    """
    addressCounty: str | None = Field(None, examples=["Hampshire"])
    """
    The county in which the town or city is located.
    """
    postcode: str | None = Field(None, examples=["M12 4AF"])
    """
    The postal code for the address.
    """
    addressCountry: str | None = Field(None, examples=["United Kingdom"])
    """
    The country of the address.
    """
    organisation: str | None = Field(None, examples=["Tech Corp"])
    """
    The name of the organisation associated with the individual.
    """
    organisationType: str | None = Field(None, examples=["Private Company"])
    """
    The type or nature of the organisation.
    """
    role: str | None = Field(None, examples=["Agent"])
    """
    The individual's role or position within the organisation.
    """
    telephoneNumber: str | None = Field(None, examples=["+447123456789"])
    """
    The primary telephone contact number.
    """
    otherPhoneNumber: str | None = Field(None, examples=["+447123456789"])
    """
    An alternate or secondary phone number.
    """
    faxNumber: str | None = Field(None, examples=["+447123456789"])
    """
    A fax contact number.
    """
    emailAddress: str | None = Field(None, examples=["john.doe@example.com"])
    """
    The primary email address for contact.
    """
    webAddress: str | None = Field(None, examples=["https://www.example.com"])
    """
    Website address or URL.
    """
    serviceUserType: ServiceUserType
    """
    Type or category of the service user.
    """
    caseReference: str = Field(..., examples=["BC0510001"])
    """
    Reference number for a particular case or incident.
    """
    sourceSystem: str = Field(..., examples=["ODT", "Horizon"])
    """
    The originating system from where the data was sourced.
    """
    sourceSuid: str = Field(..., examples=["12345"])
    """
    Unique identifier from the source system.
    """
