# generated by datamodel-codegen:
#   filename:  case-schedule.schema.json
#   timestamp: 2023-12-14T15:01:30+00:00

from __future__ import annotations

from pydantic import BaseModel


class CaseSchedule(BaseModel):
    """
    ???
    """
