branch: master
directory:
- ./infrastructure
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- terraform
quiet: true
secrets-scan-file-type: []
