repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      # - id: terraform_docs
      # - id: terraform_tflint
      #   args:
      #     - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      #     - --args=--call-module-type=all
      # - id: terraform_checkov
      #   args:
      #     - --args=--config-file=__GIT_WORKING_DIR__/.checkov.yaml
