parameters:
  agentPool: ''
  env: ''
  activateTriggers: false
  runUnitTests: true
  runIntegrationTests: True
  runEndToEndTests: true

##
# Deploy Azure Synapse
##
jobs:
- job: Deploy_Synapse
  pool: ${{ parameters.agentPool }}

  steps:
  - checkout: self
    clean: true
  - task: AzureCLI@2
    displayName: 'Testing'
    inputs:
      azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "testing"