parameters:
  agentPool: ''
  env: ''
  appName: ''

##
# Deploy Azure Synapse
##
jobs:
- job: DeployFunctionAppJob
  pool: ${{ parameters.agentPool }}
  timeoutInMinutes: 0 # Max timeout
  steps:
  # Checkout the Github repo, in this case ODW-Service.
  - checkout: self
    displayName: 'Checkout repo'
  
  # Switch to functions directory and create a file containing a list of all files in the top level folder.
  - script: |
      cd $(Build.SourcesDirectory)/functions
      find . -maxdepth 1 -type f | sed 's|^\./||' > $(Build.SourcesDirectory)/functions/filelist.txt
    displayName: 'Creating top level files list'
  
  # Create a zip file of all the files in the filelist.
  - script: |
      cd $(Build.SourcesDirectory)/functions
      cat $(Build.SourcesDirectory)/functions/filelist.txt | xargs zip -r $(Build.ArtifactStagingDirectory)/functions.zip
    displayName: 'Archive top level files'
  
  # Publish the zip file as an artifact to be used further in the pipeline.
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'FunctionCode'
  
  # Download the artifact first - the zip file.
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/download_function_code.yaml

  # Use the Azure CLI to deploy the zip file to the Function App in Azure.
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/deploy_to_function_app.yaml
    parameters:
      environment: ${{ parameters.env }}
      armServiceConnectionName: "Azure Devops Pipelines - ODW ${{ upper(parameters.env) }} - Infrastructure"
      resourceGroup: 'pins-rg-function-app-odw-${{ parameters.env }}-uks'
      functionApp: 'pins-${{ parameters.appName }}-odw-${{ parameters.env }}-uks'
      zipFile: '$(System.ArtifactsDirectory)/FunctionCode/functions.zip'
