parameters:
  agentPool: ''
  env: ''
  activateTriggers: false
  runUnitTests: true
  runIntegrationTests: True
  runEndToEndTests: true

##
# Deploy Azure Synapse
##
jobs:
- job: DeploySynapse
  # This job cannot be templated because the condition needs to be evaluated at runtime
  pool: ${{ variables.agentPool }}
  steps:
  - checkout: self
    clean: true
  - task: AzureCLI@2
    displayName: 'Testing'
    inputs:
      azureSubscription: 'ODW ${{ upper(variables.env) }} - Infrastructure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "testing"