parameters:
  agentPool: ''
  env: ''
  activateTriggers: false
  primaryWorkspace: true

variables:
- name: sourceWorkspaceName
${{ if eq(parameters.primaryWorkspace, true) }}:
  value: 'pins-synw-odw-dev-uks'
${{ else }}:
  value: 'pins-synw-odw-dev-ukw'
- name: overridesFileName
  value: TemplateParametersForWorkspace.json
- name: devDataLakeName
  value: pinsstodwdevuks9h80mb
- name: artifactName
  value: synapse-release
- name: publishBranchName
  value: 'workspace_publish'
##
# Deploy Azure Synapse
##
jobs:
- job: DeploySynapseJob
  pool: ${{ parameters.agentPool }}
  steps:
  # Checkout repo
  - checkout: self
    displayName: 'Checkout'
  # Login to Azure using Terraform service principal
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/get-synapse-details.yaml
    parameters:
      env: ${{ parameters.env }}
      pythonVersion: 3
      failoverDeployment: false
  # Set source branch
  - template: steps/branch-set-source.yaml
    parameters:
      branchName: $(Build.SourceBranch)

  # Switch to the Synapse Workspace publish branch
  - template: steps/branch-switch.yaml
    parameters:
      branchName: ${{ variables.publishBranchName }}
      showDirectory: $(Build.SourcesDirectory)/${{ variables.sourceWorkspaceName }}

  # Copy Synapse Workspace ARM template files to artifact directory
  - task: CopyFiles@2
    displayName: 'Create Release Artifacts'
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/${{ variables.sourceWorkspaceName }}
      contents: |
        TemplateForWorkspace.json
        TemplateParametersForWorkspace.json
      targetFolder: $(Build.ArtifactStagingDirectory)

  # Switch back to the source branch
  - template: steps/branch-switch.yaml
    parameters:
      branchName: $(source_branch)
      showDirectory: $(Build.SourcesDirectory)

  # Pre-Override Replacement
  - template: steps/synapse-parameters-override.yaml
    parameters:
      overrideFind: ${{ variables.devDataLakeName }}
      overrideReplace: $(SetVariables.data_lake_account_name)
      templateParametersOverridesFileName: ${{ variables.overridesFileName }}
      workingDirectory: $(Build.ArtifactStagingDirectory)

  # Publish pipeline artifacts
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ${{ variables.artifactName }}
    displayName: 'Publish Artifacts'