parameters:
  agentPool: ''
  env: ''
  activateTriggers: false
  runUnitTests: true
  runIntegrationTests: True
  runEndToEndTests: true

##
# Deploy Azure Synapse
##
jobs:
- job: DeploySynapseJob
  pool: ${{ parameters.agentPool }}
  steps:
  # Checkout repo
  - checkout: self
    displayName: 'Checkout'
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/generate-azure-synapse-variables.yaml
    parameters:
      env: ${{ parameters.env }}
