parameters:
  agentPool: ''
  env: ''

##
# Deploy Infrastructure
##
jobs:
- job: DeployInfrastructureJob
  pool: ${{ parameters.agentPool }}
  steps:
  # Checkout repo
  - checkout: self
    displayName: 'Checkout Repo'

  # Install required packages
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/install-tflint.yaml
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/install-checkov.yaml

  # Login to Azure using Terraform service principal
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml

  # Run terraform init
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/terraform-init.yaml
    parameters:
      environment: ${{ parameters.env }}
      workingDirectory: infrastructure

  # Run Terraform format
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/terraform-format.yaml
    parameters:
      workingDirectory: infrastructure

  # Run Terraform validate
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/terraform-validate.yaml
    parameters:
      workingDirectory: infrastructure

  # Run TFLint
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/tflint-validate.yaml
    parameters:
      configFilePath: $(Build.Repository.LocalPath)/.tflint.hcl
      workingDirectory: infrastructure

  # Run Checkov
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/checkov-validate.yaml
    parameters:
      framework: terraform
      workingDirectory: infrastructure
