parameters:
  agentPool: ''
  env: ''

##
# Run Synapse E2E tests
##
jobs:
- job: RunSynapseE2ETestsJob
  pool: ${{ parameters.agentPool }}
  timeoutInMinutes: 0 # Max timeout
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      export SYNAPSE_ENDPOINT="${{ format('https://pins-synw-odw-{0}-uks.dev.azuresynapse.net/', lower(parameters.env)) }}"
      export CREDENTIAL_NAME="${{ format('https://dev.azuresynapse.net/.default', lower(parameters.env)) }}"
      echo $SYNAPSE_ENDPOINT
      echo $CREDENTIAL_NAME
      python3 -m pytest $(Build.SourcesDirectory)/tests/e2e_test/test_e2e_pln_master_test.py::TestE2EPlnMasterTest::test_pln_master_test_pipeline -vv -rP --junitxml=e2e-test-results.xml --client_id="$servicePrincipalId" --client_secret="$servicePrincipalKey" --tenant="$tenantId"
    displayName: 'Run E2E Tests with pytest'
  
  - script: |
      set -e
      echo "Installing ODBC Driver 18 for SQL Server..."
      
      # Check current state
      echo "Current package state:"
      dpkg -l | grep -i odbc || echo "No ODBC packages found"
      
      # Fix any broken packages first
      echo "Fixing broken packages..."
      sudo apt --fix-broken install -y || echo "Fix-broken failed, continuing..."
      
      # Remove conflicting packages
      echo "Removing potentially conflicting ODBC packages..."
      sudo apt-get remove -y unixodbc-common unixodbc unixodbc-dev odbcinst odbcinst1debian2 libodbc1 || echo "Removal completed"
      
      # Clean package cache
      sudo apt-get clean
      sudo apt-get autoremove -y
      
      # Install Microsoft signing key
      echo "Adding Microsoft signing key..."
      curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      
      # Add Microsoft repository
      echo "Adding Microsoft repository..."
      curl -sSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
      
      # Update package list
      echo "Updating package list..."
      sudo apt-get update
      
      # Install ODBC Driver 18 and dependencies together
      echo "Installing ODBC Driver 18 and dependencies..."
      sudo DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
      
      # Install required Python packages
      echo "Installing Python packages..."
      pip3 install --user pyodbc azure-identity azure-storage-blob python-dotenv
      
      echo "ODBC Driver installation completed"
      
      # Verify installation
      echo "Verifying ODBC drivers installation..."
      echo "Available drivers:"
      odbcinst -q -d || echo "No drivers configuration found"
      
      # Check specific drivers
      if odbcinst -q -d -n "ODBC Driver 18 for SQL Server"; then
        echo "✓ ODBC Driver 18 for SQL Server found"
      else
        echo "✗ ODBC Driver 18 for SQL Server not found"
      fi
      
      if odbcinst -q -d -n "ODBC Driver 17 for SQL Server"; then
        echo "✓ ODBC Driver 17 for SQL Server found"
      else
        echo "✗ ODBC Driver 17 for SQL Server not found"
      fi
      
      # List all installed ODBC-related packages
      echo "Installed ODBC packages:"
      dpkg -l | grep -i odbc
    displayName: 'Install ODBC Driver 18 and Dependencies'
    
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      export ENV=${{ parameters.env }}
      python3 $(Build.SourcesDirectory)/tests/e2e_test/validate_e2e_results.py ${{ parameters.env }}
    displayName: 'Validate E2E Test Results using Python SynapseUtil'
