parameters:
  agentPool: ''
  env: ''

##
# Run Synapse E2E tests
##
jobs:
- job: RunSynapseE2ETestsJob
  pool: ${{ parameters.agentPool }}
  timeoutInMinutes: 0 # Max timeout
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      export SYNAPSE_ENDPOINT="${{ format('https://pins-synw-odw-{0}-uks.dev.azuresynapse.net/', lower(parameters.env)) }}"
      export CREDENTIAL_NAME="${{ format('https://dev.azuresynapse.net/.default', lower(parameters.env)) }}"
      echo $SYNAPSE_ENDPOINT
      echo $CREDENTIAL_NAME
      python3 -m pytest $(Build.SourcesDirectory)/tests/e2e_test/test_e2e_pln_master_test.py::TestE2EPlnMasterTest::test_pln_master_test_pipeline -vv -rP --junitxml=e2e-test-results.xml --client_id="$servicePrincipalId" --client_secret="$servicePrincipalKey" --tenant="$tenantId"
    displayName: 'Run E2E Tests with pytest'
  
  - task: PublishTestResults@2
    displayName: 'Publish E2E Test Results'
    condition: always()
    inputs:
      testResultsFiles: 'e2e-test-results.xml'
      testRunTitle: 'E2E Master Pipeline Tests'
      failTaskOnFailedTests: true
  
  - task: AzureCLI@2
    displayName: 'Validate E2E Test Results'
    inputs:
      azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -e  # Exit immediately if any command fails
        
        echo "Starting automated E2E test results verification..."
        echo "===================================================="
        
        # Define workspace name based on environment
        WORKSPACE_NAME="pins-synw-odw-${{ parameters.env }}-uks"
        
        echo "Environment: ${{ parameters.env }}"
        echo "Workspace: $WORKSPACE_NAME"
        echo ""
        
        # Make the script executable and run it
        chmod +x $(Build.SourcesDirectory)/scripts/verify-e2e-test-results.sh
        $(Build.SourcesDirectory)/scripts/verify-e2e-test-results.sh "$WORKSPACE_NAME" 2 10
        
        echo ""
        echo "E2E test verification completed successfully!"
        echo "All tests passed - pipeline can proceed."
