parameters:
  agentPool: ''
  env: ''

##
# Run ODW Package integration tests
##
jobs:
- job: RunODWPackageUnitTestsJob
  pool: ${{ parameters.agentPool }}
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      sudo apt-get install unixodbc-dev
      sudo curl -fsSL https://aka.ms/install-azd.sh | bash
      export SYNAPSE_ENDPOINT="${{ format('https://pins-synw-odw-{0}-uks.dev.azuresynapse.net/', lower(parameters.env)) }}"
      export CREDENTIAL_NAME="${{ format('https://dev.azuresynapse.net/.default', lower(parameters.env)) }}"
      echo $SYNAPSE_ENDPOINT 
      echo $CREDENTIAL_NAME
      python3 -m pytest $(Build.SourcesDirectory)/odw/test/integration_test -vv -rP -n 4
    displayName: 'pytest'
