parameters:
  agentPool: ''
  env: ''

##
# Run Synapse smoke tests
##
jobs:
- job: RunSynapseSmokeTestsJob
  pool: ${{ parameters.agentPool }}
  steps:
  - checkout: self
    clean: true
  - task: AzureCLI@2
    displayName: 'Testing'
    inputs:
      azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "No tests to run"