parameters:
  agentPool: ''
  env: ''

##
# Run Synapse E2E tests
##
jobs:
- job: RunSynapseE2ETestsJob
  pool: ${{ parameters.agentPool }}
  timeoutInMinutes: 0 # Max timeout
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      export SYNAPSE_ENDPOINT="${{ format('https://pins-synw-odw-{0}-uks.dev.azuresynapse.net/', lower(parameters.env)) }}"
      export CREDENTIAL_NAME="${{ format('https://dev.azuresynapse.net/.default', lower(parameters.env)) }}"
      echo $SYNAPSE_ENDPOINT
      echo $CREDENTIAL_NAME
      python3 -m pytest $(Build.SourcesDirectory)/tests/e2e_test/test_e2e_pln_master_test.py::TestE2EPlnMasterTest::test_pln_master_test_pipeline -vv -rP --junitxml=e2e-test-results.xml --client_id="$servicePrincipalId" --client_secret="$servicePrincipalKey" --tenant="$tenantId"
    displayName: 'Run E2E Tests with pytest'
  
  - script: |
      # Install ODBC Driver 18 for SQL Server
      echo "Installing ODBC Driver 18 for SQL Server..."
      sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      sudo curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
      sudo apt-get update
      sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
      sudo apt-get install -y unixodbc-dev
      
      # Install required Python packages
      pip3 install pyodbc azure-identity azure-storage-blob python-dotenv
      
      echo "ODBC Driver 18 installation completed"
      
      # Verify installation
      odbcinst -q -d -n "ODBC Driver 18 for SQL Server" || echo "Driver 18 not found"
      odbcinst -q -d -n "ODBC Driver 17 for SQL Server" || echo "Driver 17 not found"
    displayName: 'Install ODBC Driver 18 and Dependencies'
    
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      export ENV=${{ parameters.env }}
      python3 $(Build.SourcesDirectory)/tests/e2e_test/validate_e2e_results.py ${{ parameters.env }}
    displayName: 'Validate E2E Test Results using Python SynapseUtil'
