parameters:
  agentPool: ''

##
# Build and deploy the ODW Python package
##
stages:
- stage: BuildDeployODWPackage
  displayName: 'Build and deploy the ODW Python package'
  condition: |
    not(or(failed(), canceled()))
  jobs:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/run-ado-script-tests.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
