parameters:
  agentPool: ''
  env: ''
  armServiceConnectionName: ''
  failoverDeployment: false
  outputsFileName: ''

##
# Deploy Infrastructure only if a modification has been detected in the codebase
##
stages:
- stage: DeployInfrastructure
  displayName: 'Deploy Infrastructure to the ${{ parameters.env }} environment'
  condition: |
    and(
      not(or(failed(), canceled())),
      eq(dependencies.PreDeploy.outputs['PreDeploymentJob.checkModifiedComponents.infrastructureModified'], true)
    )
  jobs:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/deploy-infrastructure.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
      env: ${{ parameters.env }}
      armServiceConnectionName: ${{ parameters.armServiceConnectionName }}
      failoverDeployment: ${{ parameters.failoverDeployment }}
      outputsFileName: ${{ parameters.outputsFileName }}