parameters:
  agentPool: ''
  env: ''

##
# Deploy Infrastructure only if a modification has been detected in the codebase
##
stages:
- stage: Deploy_Infrastructure
  displayName: 'Deploy Infrastructure to the ${{ parameters.env }} environment'
  dependsOn: Pre_Deploy
  condition: eq(dependencies.PreDeploy.outputs['PreDeploymentChecks.checkModifiedComponents.infrastructureModified'], true)
  jobs:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/deploy-infrastructure.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
      env: ${{ parameters.env }}