parameters:
  agentPool: ''
  env: ''

##
# Deploy Azure Synapse only if a modification has been detected in the codebase
##
stages:
- stage: Deploy_Synapse
  displayName: 'Deploy Synapse to the ${{ parameters.env }} environment'
  dependsOn: Deploy_Infrastructure
  condition: eq(dependencies.Pre_Deploy.outputs['PreDeploymentChecks.checkModifiedComponents.synapseModified'], true)
  jobs:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/deploy-synapse.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
      env: ${{ parameters.env }}
      activateTriggers: false
      runUnitTests: true
      runIntegrationTests: True
      runEndToEndTests: true