parameters:
  agentPool: ''
  env: ''
  armServiceConnectionName: ''
  fullDeployment: false
  adoEnvName: ''

##
# Deploy Azure Synapse only if a modification has been detected in the codebase
##
stages:
- stage: DeploySynapse
  displayName: 'Deploy Synapse to the ${{ parameters.env }} environment'
  condition: not(or(failed(), canceled()))
  jobs:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/deploy-synapse.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
      env: ${{ parameters.env }}
      armServiceConnectionName: ${{ parameters.armServiceConnectionName }}
      activateTriggers: false
      runUnitTests: true
      runIntegrationTests: True
      runEndToEndTests: true
      fullDeployment: ${{ parameters.fullDeployment }}
      adoEnvName: ${{ parameters.adoEnvName }}