parameters:
  agentPool: ''

##
# Check which components need to be deployed
##
stages:
- stage: Pre_Deploy
  displayName: 'Pre-deployment checks to work out what needs to be deployed'
  jobs:
  - job: PreDeploymentChecks
    pool: ${{ parameters.agentPool }}
    steps:
    - checkout: 'self'
      fetchDepth: 0
    - template: steps/check-which-component-is-modified.yaml
