parameters:
  env: ''

##
# Wait for admins to approve this stage before proceeding with subsequent stages
##
stages:
- stage: WaitForApproval
  displayName: Wait For Approval Before Deploying
  condition: eq(parameters.env, 'dev')
  jobs:
  - deployment: WaitForApprovalJob
    displayName: Wait For Approval
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Approved"
            displayName: Approved Message
