name: Synapse PR

parameters:
- name: runTests
  type: boolean
  default: true

pr:
- dev
- testing
#- main

schedules:
- cron: '0 19 * * 1-5' # cron syntax defining a schedule. At 7pm every week day
  displayName: Daily testing branch run
  branches:
    include:
    - testing
  always: true
  batch: false

variables:
- name: branchName
  value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
- name: env
  ${{ if eq(variables.branchName, 'dev') }}:
    value: dev
  ${{ elseif eq(variables.branchName, 'testing') }}:
    value: test
  #${{ elseif eq(variables.branchName, 'main') }}:
  #  env: prod
  ${{ else }}:
    value: dev
- name: agentPool
  value: 'pins-agent-pool-odw-${{ variables.env }}-uks'
- name: azureSubscription
  value: 'pins-agent-pool-odw-${{ variables.env }}-uks'
- group: Terraform ${{ variables.env }}

stages:
- template: stages/pre-deployment.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}

- template: stages/conditional-deployment-infrastructure.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}
- template: stages/conditional-deployment-functionapp.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}
- template: stages/conditional-deployment-synapse.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}
- ${{ if eq(parameters.runTests, true) }}:
  - template: stages/conditional-run-tests.yaml
    parameters:
      agentPool: ${{ variables.agentPool }}
      env: ${{ variables.env }}
