name: Synapse PR

pr:
- dev
- testing
#- main

variables:
  branchName: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  ${{ if eq(variables.branchName, 'dev') }}:
    env: dev
  ${{ elseif eq(variables.branchName, 'testing') }}:
    env: test
  #${{ elseif eq(variables.branchName, 'main') }}:
  #  env: prod
  ${{ else }}:
    env: dev
  agentPool: 'pins-agent-pool-odw-${{ variables.env }}-uks'
  azureSubscription: 'pins-agent-pool-odw-${{ variables.env }}-uks'

stages:
- stage: PreDeploy
  displayName: 'Pre-deployment checks to work out what needs to be deployed'
  jobs:
  - job: PreDeploymentChecks
    pool: ${{ variables.agentPool }}
    steps:
    - checkout: 'self'
      fetchDepth: 0
    - template: steps/check-which-component-is-modified.yaml

- template: stages/conditional-deployment-infrastructure.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}
- template: stages/conditional-deployment-synapse.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}
