name: Synapse PR

pr:
- dev
- test
#- main

variables:
  branchName: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  ${{ if eq(variables.branchName, 'dev') }}:
    env: dev
  ${{ elseif eq(variables.branchName, 'testing') }}:
    env: test
  #${{ elseif eq(variables.branchName, 'main') }}:
  #  env: prod
  ${{ else }}:
    env: null

stages:
- stage: validateBuildBranch
  displayName: 'Check that the build branch is correct'
  jobs:
  - task: AzureCLI@2
    displayName: 'Fail pipeline'
    condition: eq(variables.env, null)
    inputs:
      azureSubscription: 'ODW ${{ upper(parameters.env) }} - Infrastructure'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "##vso[task.logissue type=error]The pipeline can only run against the following branches ['dev', 'testing', 'main'] but tried to run against variables['Build.SourceBranch']"
        exit 1
    condition: eq(variables.env, null)
- stage: DeploySynapse
  # This needs to be updated to deploy to the build environment once that has been created
  displayName: 'Deploy Synapse to the ${{ variables.env }} environment'
  jobs:
  - template: jobs/deploy-synapse.yaml
    parameters:
      agentPool: 'pins-agent-pool-odw-${{ variables.env }}-uks'
      env: ${{ variables.env }}
      activateTriggers: false
      runUnitTests: true
      runIntegrationTests: True
      runEndToEndTests: true
