name: Synapse dev PR

pr:
- dev

stages:
- stage: DeploySynapse
  # This needs to be updated to deploy to the build environment once that has been created
  displayName: 'Deploy Synapse to the dev environment'
  jobs:
  - template: pipelines/jobs/deploy-synapse.yaml
    parameters:
      agentPool: 'pins-agent-pool-odw-dev-uks'
      env: dev
      activateTriggers: false
      runUnitTests: true
      runIntegrationTests: True
      runEndToEndTests: true
