pr: none

trigger: none

pool: 'pins-agent-pool-odw-dev-uks'

stages:
  - stage: Build
    displayName: Build Code
    jobs:
    - job: Build
      steps:
      - checkout: feat/ci-cd-testing
      - task: ArchiveFiles@2
        displayName: Archive files
