variables:
- name: sourceFolder
  value: '$(System.DefaultWorkingDirectory)/workspace'

- name: target_folder
  value: '$(Build.ArtifactStagingDirectory)'

- name: storage_account_name
  value: $(DATA_LAKE_STORAGE)

- name: storage_container
  value: 'test'

pr: none

trigger: none

pool: 'pins-agent-pool-odw-dev-uks'

stages:
  - stage: Build
    displayName: Build Code

    jobs:
    - job: Build

      steps:
      - checkout: self

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Check out the main branch
            git fetch origin

            # Get back to the original branch
            # git checkout $(Build.SourceBranchName)
            git checkout feat/ci-cd-testing

            # List added files compared to the main branch
            $addedFiles = git diff --name-only --diff-filter=A origin/main..origin/feat/ci-cd-testing -- workspace/ |
                          Where-Object { $_ -match '\.json$' }

            # Write to a file for archiving
            $addedFiles | Out-File added_files_list.txt

            # Show the contents of the file in the console
            Write-Output "Files added in feat/ci-cd-testing compared to main:"
            Get-Content added_files_list.txt

            foreach ($file in $addedFiles) {
              $sourcePath = "$(Build.SourcesDirectory)/$file"  # Correct source path relative to repository root
              $destinationPath = "$(Build.ArtifactStagingDirectory)/$file"
              
              # Ensure the destination directory exists
              New-Item -ItemType Directory -Path (Split-Path -Path $destinationPath) -Force -ErrorAction SilentlyContinue
              
              # Copy the file
              if (Test-Path $sourcePath) {
                  Copy-Item -Path $sourcePath -Destination $destinationPath -Force
              } else {
                  Write-Output "Source file not found: $sourcePath"
              }
            }

            # List the files in the artifact staging directory to confirm they've been copied
            Write-Output "Files in $(Build.ArtifactStagingDirectory):"
            Get-ChildItem -Recurse -Path "$(Build.ArtifactStagingDirectory)"




      # - task: CopyFiles@2
      #   displayName: 'Copy files to staging directory'
      #   inputs:
      #     SourceFolder: '$(source_folder)'
      #     Contents: '**'
      #     TargetFolder: '$(target_folder)'

      # - script: |
      #     echo 'Listing files...'
      #     ls -R '$(Build.ArtifactStagingDirectory)'

      #   displayName: 'Listing files...'

      # - task: AzureCLI@2
      #   displayName: 'Send to Azure storage'
      #   inputs:
      #     azureSubscription: '$(armServiceConnectionName)'
      #     scriptType: 'bash'
      #     scriptLocation: 'inlineScript'
      #     inlineScript: |
      #       az storage blob upload-batch \
      #       --account-name $(storage_account_name) \
      #       --destination $(storage_container) \
      #       --source $(Build.ArtifactStagingDirectory) \
      #       --pattern '*' \
      #       --overwrite true \
      #       --auth-mode login