name: Nightly Data Validation Tests - Test

# This is the nightly data validation pipeline against the test environment
# Runs the pln_master_test Synapse pipeline for end-to-end testing
# Scheduled to run daily at 11pm

# No manual triggers - this pipeline runs only on schedule
trigger: none
pr: none

# Schedule for daily execution at 11pm
schedules:
- cron: '0 23 * * *' # Daily at 11pm UTC
  displayName: Daily E2E data validation tests at 11pm
  branches:
    include:
    - main
  always: true
  batch: false

# Import the common templates repository
resources:
  repositories:
  - repository: odw-common
    type: github
    name: Planning-Inspectorate/odw-common
    endpoint: Planning-Inspectorate
    ref: main

variables:
- name: env
  value: test
- name: variableGroupName
  value: "Terraform Test"
- name: agentPool
  value: "pins-agent-pool-odw-${{ variables.env }}-uks"
- group: ${{ variables.variableGroupName }}

stages:
# Run E2E data validation tests
- template: stages/run-e2e-tests.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}

