repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: commit-msg
        name: commit-msg-formatter
        args: [--commit-msg-filename, $1]
        description: "Enforces proper commit message format"
        entry: "commitlint --edit $1"
        language: system
        types: [commit]

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-branch-name
        name: check-branch-name
        description: "Checks if the branch name follows the convention"
        entry: "./check_branch_name.sh"
        language: script
        types: [push]
