parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
    - Build
    - Dev
    - Test
    - Prod

variables:
- group: Terraform ${{ parameters.environment }}
- name: environment
  value: ${{ lower(parameters.environment) }}
- name: poolName
  value: ${{ format('pins-agent-pool-odw-{0}-uks', lower(parameters.environment)) }}

pr: none

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure
    exclude:
    - '**/README.md'

stages:
  - stage: Validate
    jobs:
    - job: Validate
      pool: ${{ variables.poolName }}
      steps:
      # Checkout repo
      - checkout: self
        displayName: 'Checkout Repo'

      # Login to Azure using Terraform service principal
      - template: steps/azure-login.yaml

      # Run terraform init
      - template: steps/terraform-init.yaml
        parameters:
          environment: ${{ variables.environment }}
          workingDirectory: infrastructure

      # Run Terraform format
      - template: steps/terraform-format.yaml
        parameters:
          workingDirectory: infrastructure

      # Run Terraform validate
      - template: steps/terraform-validate.yaml
        parameters:
          workingDirectory: infrastructure

      # Run TFLint
      - template: steps/tflint-validate.yaml
        parameters:
          configFilePath: $(Build.Repository.LocalPath)/.tflint.hcl
          workingDirectory: infrastructure

      # Run Checkov
      - template: steps/checkov-validate.yaml
        parameters:
          workingDirectory: infrastructure
