name: Deployment
trigger:
  branches:
    include:
    - 'dev'
    # - 'test'
    # - 'prod'

pool:
  vmImage: ubuntu-22.04

variables:
- name: environment
  value: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}

stages:
  - stage: Deployment
    jobs:
    - job: Trigger_Platform_Integrate 
      steps:
        - script: echo ${{ variables.environment }}
      # - template: terraform-ci.yaml
      #   parameters:
      #     environment: 'dev'
      