parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
    - Dev
    - Test
    - Prod

variables:
- group: Terraform ${{ parameters.environment }}
- name: environment
  value: ${{ lower(parameters.environment) }}

pr: none

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure
    exclude:
    - '**/README.md'

pool:
  vmImage: ubuntu-22.04

stages:
  - stage: Validate
    jobs:
    - job: Validate
      steps:
      # Checkout repo
      - checkout: self
        displayName: 'Checkout Repo'

      # Install required packages
      - template: steps/install-tflint.yaml
      - template: steps/install-checkov.yaml

      # Login to Azure using Terraform service principal
      - template: steps/azure-login.yaml
        parameters:
          servicePrincipalId: $(AZURE_SERVICE_PRINCIPAL_ID)
          servicePrincipalSecret: $(AZURE_SERVICE_PRINCIPAL_SECRET)
          subscriptionId: $(SUBSCRIPTION_ID)
          tenantId: $(AZURE_TENANT_ID)

      # Run terraform init
      - template: steps/terraform-init.yaml
        parameters:
          armClientId: $(AZURE_SERVICE_PRINCIPAL_ID)
          armClientSecret: $(AZURE_SERVICE_PRINCIPAL_SECRET)
          armSubscriptionId: $(SUBSCRIPTION_ID)
          armTenantId: $(AZURE_TENANT_ID)
          environment: ${{ variables.environment }}

      # Run Terraform format
      - template: steps/terraform-format.yaml
        parameters:
          workingDirectory: infrastructure

      # Run Terraform validate
      - template: steps/terraform-validate.yaml
        parameters:
          workingDirectory: infrastructure

      # Run TFLint
      - template: steps/tflint-validate.yaml
        parameters:
          configFilePath: $(Build.Repository.LocalPath)/.tflint.hcl
          workingDirectory: infrastructure

      # Run Checkov
      - template: steps/checkov-validate.yaml
        parameters:
          framework: terraform
          workingDirectory: infrastructure
