name: Deployment
trigger:
  branches:
    include:
    - 'dev'
    # - 'test'
    # - 'prod'

pool:
  vmImage: ubuntu-22.04

variables:
  BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

stages:
  - stage: Trigger Platform Integrate 
    jobs:
    - job: Trigger Platform Integrate 
      steps:
      - template: terraform-ci.yaml
        parameters:
          environment: $(BRANCH_NAME)
    - job: Trigger Platform Deploy 
      steps:
      - template: terraform-cd.yaml
        parameters:
          environment: $(BRANCH_NAME)