# List of Azure modules are here https://azure.github.io/azure-sdk/releases/latest/all/python.html
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "HELLO" 
      ls -l $(Build.SourcesDirectory)/workspace/testing/tests
      pip install pandas pyarrow pytest pytest-azurepipelines aiohttp pyodbc azure-storage-blob azure-keyvault-secrets azure-identity azure-storage-file-datalake azure-synapse
     
      pytest -vv --rootdir=$(Build.SourcesDirectory)/workspace/testing/tests --ignore=$(Build.SourcesDirectory)/functions
    displayName: 'pytest'
