# List of Azure modules are here https://azure.github.io/azure-sdk/releases/latest/all/python.html
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      pip install pandas pyarrow pytest pytest-azurepipelines aiohttp pyodbc azure-storage-blob azure-keyvault-secrets azure-identity azure-storage-file-datalake azure-synapse azure-mgmt-resource
      cd $(Build.SourcesDirectory)/workspace/testing/tests
      pytest -vv -rP
    displayName: 'pytest'
