parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
      - Dev
      - Test
trigger: none
pr: none
pool: pins-agent-pool-odw-dev-uks
variables:
  - group: Terraform ${{ parameters.environment }}
  - name: armServiceConnectionName
    value: ${{ format('Azure DevOps Pipelines - ODW {0} - Infrastructure', upper(variables.environment)) }}
  - name: environment
    value: ${{ lower(parameters.environment) }}
  - name: resourceGroup
    value: 'pins-rg-function-app-odw-${{ variables.environment }}-uks'
  - name: poolName
    value: ${{ format('pins-agent-pool-odw-{0}-uks', lower(parameters.environment)) }}
stages:
  - stage: Output
    displayName: Terraform Output ${{ parameters.environment }}
    jobs:
    - job: Output
      displayName: Terraform Output
      pool: ${{ variables.poolName }}
      steps:
      - checkout: self
        displayName: Checkout
      - template: ../steps/azure-login.yaml
    - job: RunPyTests
      displayName: Run PyTests
      steps:
        - script: |
            pip install pytest
            pip install pandas
            pip install pyarrow
          displayName: Install dependencies
        - script: |
            pytest $(Build.SourcesDirectory)pytests.py
          displayName: Run PyTests
