---
trigger: none

pr: none

pool: 'pins-agent-pool-odw-dev-uks'

variables:
  - name: environment
    value: dev
  - name: armServiceConnectionName
    value: ${{ format('Azure DevOps Pipelines - ODW {0} - Infrastructure', upper(variables.environment)) }}
  - name: resourceGroup
    value: 'pins-rg-function-app-odw-${{ variables.environment }}-uks'
  - name: poolName
    value: 'pins-agent-pool-odw-${{ variables.environment }}-uks'
  - name: PYTHON_VERSION
    value: '3.8'

stages:
- stage: Test
  jobs:
  - job: RunPyTests
    displayName: 'Run PyTests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true

    - script: |
        pip install pytest
        pip install pandas
        pip install pyarrow
      displayName: 'Install dependencies'

    # - script: |
    #     pytest $(Build.SourcesDirectory)/pytests.py
    #   displayName: 'Run PyTests'
