parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
      - Dev
      - Test
trigger: none
pr: none
pool: pins-agent-pool-odw-dev-uks
variables:
  - group: Terraform ${{ parameters.environment }}
  - name: armServiceConnectionName
    value: ${{ format('Azure DevOps Pipelines - ODW {0} - Infrastructure', upper(variables.environment)) }}
  - name: environment
    value: ${{ lower(parameters.environment) }}
  - name: resourceGroup
    value: 'pins-rg-function-app-odw-${{ variables.environment }}-uks'
  - name: poolName
    value: ${{ format('pins-agent-pool-odw-{0}-uks', lower(parameters.environment)) }}
stages:
  - stage: azure_login
    displayName: Terraform Output ${{ parameters.environment }}
    jobs:
    - job: Output
      displayName: Terraform Output
      pool: ${{ variables.poolName }}
      steps:
      - checkout: self
        displayName: Checkout
      - template: ../steps/azure-login.yaml
    - job: RunScripts
      displayName: Install & Run PyTests
      steps:
        - template: ../steps/azure-login.yaml
        - script: |
            pwd
            ls -la $(Build.SourcesDirectory)/pipelines/pytests/
          displayName: List files in the source directory
        - script: |
            export PATH="$PATH:/home/AzDevOps/.local/bin/"
            sudo apt-get install unixodbc-dev
            curl -fsSL https://aka.ms/install-azd.sh | bash
            pip install -r $(Build.SourcesDirectory)/pipelines/pytests/requirements.txt
          displayName: Install dependencies
        - script: |
            pytest $(Build.SourcesDirectory)/pipelines/pytests/pytests.py -vv -rP
          displayName: Run PyTests
