---
trigger: none

pool:
  vmImage: 'pins-agent-pool-odw-dev-uks'

variables:
  PYTHON_VERSION: '3.8'

stages:
- stage: Test
  jobs:
  - job: RunPyTests
    displayName: 'Run PyTests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pytest pytests.py
      displayName: 'Run PyTests'
