name: Code Validation

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Validate Synapse notebooks
      run: |
        export PYTHONPATH="${PYTHONPATH}:/./"
        python3 pipelines/scripts/check_notebooks_valid.py
    - name: Validate ODW Python package code styling
      run: |
        pip install flake8
        flake8 odw
