###
# This pipeline automatically deletes and recreates the dev branch when code is merged into main
###
name: Recreate the dev branch

on:
  push:
    branches:
      - main

jobs:
  recreate_dev_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Delete dev branch
      shell: bash
      run: |
        git fetch
        git checkout main
        git push -d origin dev
        set -e
        git checkout -b dev
        git push --set-upstream origin dev
