###
# This pipeline automatically deletes and recreates the dev branch when code is merged into main
###
name: Recreate the dev branch

on:
  push:
    branches:
      - main

jobs:
  recreate_dev_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Delete dev branch
      shell: bash
      run: |
        set -e
        git fetch
        git checkout main
        devBranches=$(git ls-remote --heads origin dev)
        echo $devBranches
        if [[ -z "$devBranches" ]]; then
            echo "Dev branch does not exist, nothing to delete"
        else
            git push -d origin dev
        fi
        git checkout -b dev
        git push --set-upstream origin dev
