name: Check is dev branch

on:
  pull_request:
    branches: 
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from the dev branch"
          exit 1
