name: Synapse artifact archival

on:
  schedule:
    - cron: '00 9 * * mon'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Validate Synapse notebooks
      run: |
        python3 -m pip install ast2json azure-identity 
        export PYTHONPATH="${PYTHONPATH}:/./"
        python3 pipelines/scripts/archive_artifacts.py
